export const CUSTOMER_REGISTER = 'CUSTOMER_REGISTER';
export const CUSTOMER_LOGIN = 'CUSTOMER_LOGIN';
export const CUSTOMER_LOGOUT = 'CUSTOMER_LOGOUT';
export const CUSTOMER_AUTH = 'CUSTOMER_AUTH';
export const CUSTOMER_CHANGE_PASSWORD = 'CUSTOMER_CHANGE_PASSWORD';
export const CUSTOMER_FORGOTPASSWORD = 'CUSTOMER_FORGOTPASSWORD';
export const CUSTOMER_RESETPASSWORD = 'CUSTOMER_RESETPASSWORD';

export const CATEGORY_LIST = 'CATEGORY_LIST';
export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_LIST_MORE = 'PRODUCT_LIST_MORE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const GET_CART_ITEM = 'GET_CART_ITEM';
export const CLEAR_CART_ITEM = 'CLEAR_CART_ITEM';

export const CHECKOUT = 'CHECKOUT';
export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';


